// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OficinaMecanica.Api.Infrastructure.Persistence;

#nullable disable

namespace OficinaMecanica.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912171915_AddClienteAtivo")]
    partial class AddClienteAtivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DiagnosticoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EntregueEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnvioOrcamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("MockEnvioOrcamento");

                    b.Property<DateTime?>("ExecucaoIniciadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotivoRecusaOrcamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OrcamentoEnviadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusAprovacaoOrcamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotalOrcamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotalPecasInsumos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotalServicos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServicoItemPecaInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NomePecaInsumo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PecaInsumoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("OrdemServicoItensPecaInsumo");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServicoItemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecoServico")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("OrdemServicoItensServico");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.PecaInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PecasInsumos");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("OficinaMecanica.Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany("OrdensServico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaMecanica.Api.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("OrdensServico")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServicoItemPecaInsumo", b =>
                {
                    b.HasOne("OficinaMecanica.Api.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("ItensPecaInsumo")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServicoItemServico", b =>
                {
                    b.HasOne("OficinaMecanica.Api.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("ItensServico")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("OficinaMecanica.Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("OrdensServico");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("ItensPecaInsumo");

                    b.Navigation("ItensServico");
                });

            modelBuilder.Entity("OficinaMecanica.Api.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
