resources:
  - metrics-server.yaml
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
