apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_pass
  MYSQL_PASSWORD: oficina_pass
  JwtSettings__SecretKey: oficina-mecanica-tech-challenge-secret-key-2026
  AdminUserSettings__Username: admin
  AdminUserSettings__Password: Admin@123
