apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-jwt-credential
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  key: {{ required "jwt.issuer e obrigatorio" .Values.jwt.issuer | quote }}
  algorithm: HS256
  secret: {{ required "jwt.secret e obrigatorio" .Values.jwt.secret | quote }}
