name: Integracao continua

env:
  DOTNET_VERSION: 10.0.x

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore OficinaMecanica.Api.sln

      - name: Build solution
        run: dotnet build OficinaMecanica.Api.sln --configuration Release --no-restore

  test:
    name: Test
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore OficinaMecanica.Api.sln

      - name: Run tests
        run: dotnet test OficinaMecanica.Api.sln --configuration Release --no-restore --verbosity normal
